### ISSUE TITLE
reporting mAP computed for the reproduced models

### ISSUE THREAD

**Issue by aosokin** [ignacio-rocco/detectorch#2]
Hi, do you plan to add mAP on PASCAL/COCO computed by your code?
I suggest adding those to the README directly

**Comment by ignacio-rocco** [comment]
Hi, I have only tried COCO. I added the mAP to the README!

**Comment by aosokin** [comment]
Wound't it be better to add original numbers (produced by Caffe2 code) as well to show that you reproduce it well?

**Comment by ignacio-rocco** [comment]
Hi, maybe it's a bit repetitive as it's the same models running the same
operations, so the numbers match exactly.

Le sam. 10 mars 2018 20:30, Anton Osokin <notifications@github.com> a
écrit :

**Comment by aosokin** [comment]
@ignacio-rocco it just shows in numbers that you are serious. There are lots of repos online that claim that they reproduce smth, but the numbers are nowhere close. And the numbers are way more concrete compared to saying that in text.
