### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by omartin2010** [ignacio-rocco/detectorch#5]
I was hoping to get this to run on Windows10 with GPU support (enabled by [this repo](https://github.com/peterjc123/pytorch-scripts). 

I've modified bind.py a bit and am still getting this error : 
C:\...\Dev\detectorch\lib\cppcuda_cffi\src\cpp\roi_align_cpu_loop.o : fatal error LNK1107: invalid or corrupt file: cannot read at 0x3A8

Any clue what to look out for? Are you planning for Windows support?

**Comment by ignacio-rocco** [comment]
Hi, I'm sorry but I don't have Windows to try this, but hopefully you will be able to solve this problem.

It looks like the problems comes from the compilation of the cpp file called from make.sh

`g++ -I $TORCHLIBPATH -o roi_align_cpu_loop.o roi_align_cpu_loop.cpp -fPIC -shared -std=c++0x`

Maybe you need to use the Windows cl compiler? I'm sorry but I cannot help you with this. But do let me know if you find the solution.
