### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by riteshhota2008** [ignacio-rocco/detectorch#8]
Hello.

Thank you so much for your work. Really appreciate it. Best mask-RCNN implementation. 

I have completed Compiling the Coco API and RoIAlign.

I checked the demo notebook. But I was not able to understand how to run this project. 
Could you please tell me which file I need to run to get the results pdf output.

Thanks!

**Comment by ignacio-rocco** [comment]
Hi, if you run the demo notebook, the pdf should be generated when running the last cell.

**Comment by riteshhota2008** [comment]
Thanks. I tried but I am getting this error. Could you please help me out?

![image](https://user-images.githubusercontent.com/11539734/39067516-8c03e18c-44f6-11e8-8431-4bbc9f4b30a7.png)

NameError                                 Traceback (most recent call last)
<ipython-input-1-acf16cb93d48> in <module>()
      3   #      class_scores,bbox_deltas,rois,img_features=eval_model(sample)
      4 #else:
----> 5 class_scores,bbox_deltas,rois,img_features=eval_model(sample)
      6 
      7 # postprocess output:

NameError: name 'eval_model' is not defined

**Comment by ignacio-rocco** [comment]
`eval_model` is defined in the cell right before that one. You need to run the whole notebook from top to bottom, right?

**Comment by riteshhota2008** [comment]
Okay. Got it. Thanks. 
It worked.
